services:
  danimezone-site:
    image: ghcr.io/${GHCR_OWNER}/danimezone-site:latest
    pull_policy: always
    env_file:
      - ./deploy/.env
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - ONLINE_STORE_BASE_URL=${ONLINE_STORE_BASE_URL}
      - CLOUD_API_URL=${CLOUD_API_URL}
      - CLOUD_API_BASE_URL=${CLOUD_API_BASE_URL}
      - API_URL=${API_URL}
      - CLOUD_SHARED_SECRET=${CLOUD_SHARED_SECRET}
    labels:
      - traefik.enable=true
      - traefik.http.routers.danimezone-site.rule=Host(`danimezone.com`) || Host(`www.danimezone.com`)
      - traefik.http.routers.danimezone-site.entrypoints=websecure
      - traefik.http.routers.danimezone-site.tls.certresolver=letsencrypt
      - traefik.http.services.danimezone-site.loadbalancer.server.port=3000
      - traefik.http.routers.danimezone-site-http.rule=Host(`danimezone.com`) || Host(`www.danimezone.com`)
      - traefik.http.routers.danimezone-site-http.entrypoints=web
      - traefik.http.routers.danimezone-site-http.middlewares=redirect-to-https
      - traefik.http.middlewares.redirect-to-https.redirectregex.regex=^http://(.*)/(?!\\.well-known/acme-challenge/)(.*)
      - traefik.http.middlewares.redirect-to-https.redirectregex.replacement=https://$${1}/$${2}
      - traefik.http.middlewares.redirect-to-https.redirectregex.permanent=true
    networks:
      - web

  danimezone-api:
    image: ghcr.io/${GHCR_OWNER}/danimezone-api:latest
    pull_policy: always
    env_file:
      - ./deploy/.env
    environment:
      - NODE_ENV=production
      - PORT=4000
      - DATABASE_URL=${DATABASE_URL}
      - CLOUD_SHARED_SECRET=${CLOUD_SHARED_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - ONLINE_STORE_BASE_URL=${ONLINE_STORE_BASE_URL}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_FROM=${SMTP_FROM}
      - SMTP_SECURE=${SMTP_SECURE}
      - FROM_EMAIL=${FROM_EMAIL}
      - APP_NAME=${APP_NAME}
      - SUPPORT_EMAIL=${SUPPORT_EMAIL}
      - CLOUD_API_BASE_URL=${CLOUD_API_BASE_URL}
      - ENVIROMENT=${ENVIRONMENT}
    labels:
      - traefik.enable=true
      - traefik.http.routers.danimezone-api.rule=Host(`api.danimezone.com`)
      - traefik.http.routers.danimezone-api.entrypoints=websecure
      - traefik.http.routers.danimezone-api.tls.certresolver=letsencrypt
      - traefik.http.services.danimezone-api.loadbalancer.server.port=4000
      - traefik.http.routers.danimezone-api-http.rule=Host(`api.danimezone.com`)
      - traefik.http.routers.danimezone-api-http.entrypoints=web
      - traefik.http.routers.danimezone-api-http.middlewares=redirect-to-https
      - traefik.http.middlewares.redirect-to-https.redirectregex.regex=^http://(.*)/(?!\\.well-known/acme-challenge/)(.*)
      - traefik.http.middlewares.redirect-to-https.redirectregex.replacement=https://$${1}/$${2}
      - traefik.http.middlewares.redirect-to-https.redirectregex.permanent=true
    networks:
      - web

networks:
  web:
    external: true
    name: danimezone-web
