services:
  traefik:
    image: traefik:v2.11
    container_name: danimezone-traefik
    user: "0:0"
    command:
      - --providers.docker=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedbydefault=false
      - --providers.docker.watch=true
      - --log.level=DEBUG
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./deploy/letsencrypt:/letsencrypt
    networks:
      - web

  danimezone-site:
    build:
      context: ./apps/online-store
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_TELEMETRY_DISABLED: ${NEXT_TELEMETRY_DISABLED}
    env_file:
      - ./deploy/.env.local
    environment:
      - NODE_ENV=production
      - PORT=3000
    labels:
      - traefik.enable=true
      - traefik.http.routers.danimezone-site.rule=Host(`danimezone.local`)
      - traefik.http.routers.danimezone-site.entrypoints=web
      - traefik.http.services.danimezone-site.loadbalancer.server.port=3000
    networks:
      - web

  danimezone-api:
    build:
      context: ./apps/cloud-api
      dockerfile: Dockerfile
    env_file:
      - ./deploy/.env.local
    environment:
      - NODE_ENV=production
      - PORT=4000
    labels:
      - traefik.enable=true
      - traefik.http.routers.danimezone-api.rule=Host(`api.danimezone.local`)
      - traefik.http.routers.danimezone-api.entrypoints=web
      - traefik.http.services.danimezone-api.loadbalancer.server.port=4000
    networks:
      - web

networks:
  web:
    name: danimezone-web
